version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
  web:
    image: lazy_man_reminder/web
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["/backend/start.sh"]
    container_name: web
    volumes:
      - ./backend:/backend
    environment:
      DEBUG: 'true'
    ports:
      - "8000:8000"
      - "2000:2000"
    depends_on:
      - redis
      - frontend
  django-q:
    image: lazy_man_reminder/web
    container_name: task-queue
    volumes:
      - ./backend:/backend
    command: ["python", "manage.py", "qcluster"]
    depends_on:
      - redis
      - web
  frontend:
    image: lazy_man_reminder/frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/public:/frontend/public
      - ./frontend/src:/frontend/src
    ports:
      - "3000:3000"