version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
  web:
    image: lazy_man_reminder
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["/backend/start.sh"]
    container_name: web
    volumes:
      - ./backend:/backend
    environment:
      DEBUG: 'true'
    ports:
      - "8000:8000"
      - "2000:2000"
    depends_on:
      - redis
  django-q:
    image: lazy_man_reminder
    command: ["python", "manage.py", "qcluster"]
    depends_on:
      - redis
      - web
  # frontend:
  #   image: cgd2/meanwhile_web:dev
  #   command: ["npm", "start"]
  #   volumes:
  #     - ./video/static:/code/video/static
  #     - ./frontend:/code/frontend
  #   ports:
  #     - "3000:3000"