# Generated by Django 3.1 on 2021-07-29 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import todolist.models.item


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Untitled', max_length=128)),
                ('due_time', models.DateTimeField(default=todolist.models.item.one_hour_later)),
                ('status', models.CharField(default='UNDONE', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
